# Official docker image.
image: docker:latest

services:
  - docker:dind

# By default, when using docker:dind, Docker uses the vfs storage driver which copies the filesystem on every run. This is a very disk-intensive operation which can be avoided if a different driver is used, for example overlay2.

variables:
  DOCKER_DRIVER: overlay2

stages:
  - test
  - deploy

test:
  stage: test
  tags:
    - development
  only:
    - develop
  cache:
    untracked: true
    policy: pull-push
    paths:
      - ./microservices/api/node_modules
      - ./microservices/client/node_modules
      - ./microservices/database_server/node_modules
      - ./microservices/exchange_server/node_modules
      - ./microservices/load_balancer/node_modules
      - ./microservices/news_server/node_modules
      - ./microservices/socketio/node_modules
  script:
    - sudo docker-compose build --no-cache

    
step-deploy-production:
  stage: deploy
  only:
    - master
  script:
    - sudo docker image prune -f
    - sudo docker-compose build --no-cache
    - sudo docker-compose up -d --scale socketio=5 --scale nextjs=5
  tags:
    - production
  when: manual
