# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

stages:
  - test
  - deploy

test:
  stage: test
  tags:
    - development
  only:
    - develop
  script:
    - docker-compose build --no-cache
    
step-deploy-production:
  stage: deploy
  only:
    - master
  script:
    - docker-compose build --no-cache
    - docker-compose down --remove-orphans
    - docker-compose -p remora up -d --scale socketio=5
    - docker system prune -a -f
  tags:
    - production
  when: manual
