# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

stages:
  - test
  - deploy

test:
  stage: test
  tags:
    - docker
  only:
    - develop
    - production
  script:
    - docker-compose build --no-cache
    
step-deploy-production:
  stage: deploy
  only:
    - production
  script:
    - docker-compose down
    - docker-compose up -d
  tags:
    - production
  when: manual
