# Official docker image.
image: docker:latest

services:
  - docker:dind

# By default, when using docker:dind, Docker uses the vfs storage driver which copies the filesystem on every run. This is a very disk-intensive operation which can be avoided if a different driver is used, for example overlay2.

variables:
  DOCKER_DRIVER: overlay2
  PROJECT_NAME: remora
  NUM_SOCKET_SERVERS: "5"
  NUM_WEB_SERVERS: "5"

stages:
  - test
  - deploy

test:
  stage: test
  tags:
    - development
  only:
    - develop
    - master
  cache:
    untracked: true
    policy: pull-push
    paths:
      - $CI_PROJECT_DIR/microservices/api/node_modules
      - $CI_PROJECT_DIR/microservices/client/node_modules
      - $CI_PROJECT_DIR/microservices/database_server/node_modules
      - $CI_PROJECT_DIR/microservices/exchange_server/node_modules
      - $CI_PROJECT_DIR/microservices/load_balancer/node_modules
      - $CI_PROJECT_DIR/microservices/news_server/node_modules
      - $CI_PROJECT_DIR/microservices/socketio/node_modules
  script:
    - docker-compose build

    
step-deploy-production:
  stage: deploy
  only:
    - master
  script:
    - docker image prune -f
    - docker-compose stop
    - docker-compose -p $PROJECT_NAME up --build -d --scale socketio=$NUM_SOCKET_SERVERS --scale nextjs=$NUM_WEB_SERVERS
  tags:
    - production
  when: manual
