version: "3"

services:

  api:
    build: ./microservices/api
    restart: always
    command: yarn run start-dev
    environment:
      - NODE_ENV=test
      - PRODUCTION_ENV=http://localhost:3000
    volumes:
      - ./microservices/api/src:/src
      - ./microservices/api/node_modules:/node_modules
      - ./microservices/api/package.json:/package.json
    ports: 
      - "9000"
    depends_on:
      - redis

  redis:
    build: ./microservices/redis
    restart: always
    volumes: 
    - ./microservices/redis/data:/data
    ports: 
      - "6379"

  binance_exchange_usd:
    build: ./microservices/exchange_server
    restart: always
    environment:
      - DEDICATED_TO=binance
      - MAIN_COIN=USD
      - NODE_ENV=dev
    command: yarn run start-dev
    volumes:
      - ./microservices/exchange_server/src:/src
      - ./microservices/exchange_server/config:/config
    ports:
      - "7000"
    depends_on:
      - redis

  # news:
  #   build: ./microservices/news_server
  #   restart: always
  #   command: yarn run start-dev
  #   volumes:
  #     - ./microservices/news_server/src:/src
  #   ports:
  #     - "5500"
  #   depends_on:
  #     - redis
  socketio:
    build: ./microservices/socketio
    restart: always
    command: yarn run start-dev
    volumes:
      - ./microservices/socketio/src:/src
      - ./microservices/socketio/config:/config
    ports:
      - "5000"
    depends_on:
      - redis
  
  # EXECUTE DATABASE SERVER FOR BINANCE
  database_binance:
    build: ./microservices/database_server
    restart: always
    command: yarn run start-dev
    volumes:
      - ./microservices/database_server/src:/src
    environment:
      - EXCHANGE=binance
      - NODE_ENV=dev
    depends_on:
      - redis
  
  load_balancer:
    build:
      context: ./microservices/load_balancer
      dockerfile: Dockerfile-dev
    volumes: 
      - ./microservices/load_balancer/load_balancer_dev.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
      - "8080:80"
    links: 
      - api
      - socketio
    depends_on: 
      - api
      - socketio