version: "3"

services:

  api:
    build: ./microservices/api
    restart: always
    ports: 
      - "9000"
    depends_on:
      - redis

  nextjs:
    build: ./microservices/client
    restart: always
    ports: 
      - "3000"

  redis:
    build: ./microservices/redis
    restart: always
    ports: 
      - "6379"

  binance_exchange_usd:
    build: ./microservices/exchange_server
    restart: always
    environment:
      - DEDICATED_TO=binance
      - MAIN_COIN=USD
      - NODE_ENV=dev
    ports:
      - "7000"
    depends_on:
      - redis

  socketio:
    build: ./microservices/socketio
    restart: always
    ports:
      - "5000"
    depends_on:
      - redis
  
  # EXECUTE DATABASE SERVER FOR BINANCE
  database_binance:
    build: ./microservices/database_server
    restart: always
    environment:
      - EXCHANGE=binance
      - NODE_ENV=dev
    depends_on:
      - redis

  nginx:
    build: ./microservices/nginx
    restart: always
    ports:
      - "80:80"
    depends_on: 
      - socketio
      - nextjs
      - api