version: "3"

services:



  socketio_1:
    build: ./socketio
    hostname: socketio_1
    restart: always
    environment:
      - PORT=4500
      - REDIS_HOST=redis
    depends_on: 
      - redis

  redis:
    build: ./redis
    hostname: redis
    restart: always
    ports: 
    - "6379:6379"

  # mongodb:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #     MONGO_INITDB_DATABASE: REMORA
  #   volumes: 
  #     - ./mongodb/data:/data/db

  # EXECUTE GDAX SERVER FOR USD
  # gdax_exchange_usd:
  #   build: ./exchange_server
  #   hostname: gdax_exchange_usd
  #   restart: always
  #   environment:
  #     - PORT=8202
  #     - DEDICATED_TO=GDAX
  #     - MAIN_COIN=USD
  #     - REDIS_HOST=redis
  #     - NODE_ENV=production
  #   depends_on:
  #     - redis
  #   links:
  #     - redis