version: "3"

services:

  api:
    build: ./microservices/api
    restart: always
    command: yarn run start
    environment:
      - NODE_ENV=prod
    ports: 
      - "9000"
    depends_on:
      - redis

  nextjs:
    build: ./microservices/client
    command: yarn start
    environment: 
      - NODE_ENV=prod
    restart: always
    ports: 
      - "3000:3000"

  redis:
    build: ./microservices/redis
    restart: always
    volumes: 
    - ./microservices/redis/data:/data
    ports: 
      - "6379"

  binance_exchange_usd:
    build: ./microservices/exchange_server
    restart: always
    environment:
      - DEDICATED_TO=binance
      - MAIN_COIN=USD
      - NODE_ENV=prod
    command: yarn run start
    ports:
      - "7000"
    depends_on:
      - redis

  socketio:
    build: ./microservices/socketio
    restart: always
    command: yarn run start
    ports:
      - "5000"
    depends_on:
      - redis
  
  # EXECUTE DATABASE SERVER FOR BINANCE
  database_binance:
    build: ./microservices/database_server
    restart: always
    command: yarn run start
    environment:
      - EXCHANGE=binance
      - NODE_ENV=prod
    depends_on:
      - redis
  
  load_balancer:
    build: ./microservices/load_balancer
    restart: always
    ports:
      - "8080:80"
    links: 
      - api
      - socketio
    depends_on: 
      - api
      - socketio


  nginx:
    build: ./microservices/nginx
    restart: always
    ports:
      - "80:80"
    links: 
      - load_balancer
      - nextjs
    depends_on: 
      - load_balancer
      - nextjs