version: "3"

services:

  api:
    build: ./microservices/api
    restart: always
    command: yarn run start-dev
    environment:
      - NODE_ENV=dev
    volumes:
      - ./microservices/api/src:/src
      - ./microservices/api/node_modules:/node_modules
      - ./microservices/api/package.json:/package.json
    ports: 
      - "9000"
    depends_on:
      - redis

  nextjs:
    build: ./microservices/client
    restart: always
    command: yarn start
    environment: 
      - NODE_ENV=prod
    volumes:
      - ./microservices/client:/usr/src/app
    ports: 
      - "3000"

  redis:
    build: ./microservices/redis
    restart: always
    ports: 
      - "6379"

  binance_exchange_usd:
    build: ./microservices/exchange_server
    restart: always
    environment:
      - DEDICATED_TO=binance
      - MAIN_COIN=USD
      - NODE_ENV=dev
    command: yarn run start-dev
    volumes:
      - ./microservices/exchange_server/src:/src
      - ./microservices/exchange_server/config:/config
    ports:
      - "7000"
    depends_on:
      - redis

  socketio:
    build: ./microservices/socketio
    restart: always
    command: yarn run start-dev
    volumes:
      - ./microservices/socketio/src:/src
      - ./microservices/socketio/config:/config
    ports:
      - "5000"
    depends_on:
      - redis
  
  # EXECUTE DATABASE SERVER FOR BINANCE
  database_binance:
    build: ./microservices/database_server
    restart: always
    command: yarn run start-dev
    volumes:
      - ./microservices/database_server/src:/src
    environment:
      - EXCHANGE=binance
      - NODE_ENV=dev
    depends_on:
      - redis
  
  load_balancer:
    build: ./microservices/load_balancer
    volumes: 
      - ./microservices/load_balancer/load_balancer.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
      - "8080:80"
    links: 
      - api
      - socketio
    depends_on: 
      - api
      - socketio


  nginx:
    build: ./microservices/nginx
    volumes: 
      - ./microservices/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
      - "7500:80"
    links: 
      - load_balancer
    depends_on: 
      - load_balancer
      - nextjs