version: "3"

services:



  socketio_1:
    build: ./socketio
    hostname: socketio_1
    restart: always
    environment:
      - PORT=4500
      - REDIS_HOST=redis
    depends_on: 
      - redis

  redis:
    build: ./redis
    hostname: redis
    restart: always

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: REMORA
    volumes: 
      - ./mongodb/data:/data/db

  # EXECUTE BINANCE SERVER FOR ETH
  binance_exchange_eth:
    build: ./exchange_server
    hostname: binance_exchange_eth
    restart: always
    environment:
      - PORT=8002
      - DEDICATED_TO=BINANCE
      - MAIN_COIN=ETH
      - REDIS_HOST=redis
      - NODE_ENV=production
    depends_on:
      - redis
    links:
      - redis