version: "3"

services:

  nextjs:
    build: ./microservices/client
    restart: always
    volumes:
      - ./microservices/client:/opt/app
    ports: 
      - "3000"

  redis:
    build: ./microservices/redis
    restart: always
    ports: 
      - "6379"

  binance_exchange_usd:
    build: ./microservices/exchange_server
    restart: always
    environment:
      - DEDICATED_TO=binance
      - MAIN_COIN=USD
      - NODE_ENV=dev
    command: yarn run start-dev
    volumes:
      - ./microservices/exchange_server/src:/src
    ports:
      - "7000"
    depends_on:
      - redis

  socketio:
    build: ./microservices/socketio
    restart: always
    command: yarn run start-dev
    volumes:
      - ./microservices/socketio/src:/src
    ports:
      - "5000"
    depends_on:
      - redis
  
  # EXECUTE DATABASE SERVER FOR BINANCE
  database_binance:
    build: ./microservices/database_server
    restart: always
    command: yarn run start-dev
    volumes:
      - ./microservices/database_server/src:/src
    environment:
      - EXCHANGE=binance
      - NODE_ENV=dev
    depends_on:
      - redis

  nginx:
    build: ./microservices/nginx
    volumes: 
      - ./microservices/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./microservices/nginx/static:/var/www
    restart: always
    ports:
      - "8080:80"
    depends_on: 
      - socketio
      - nextjs