export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_USER_PREFERENCES = 'UPDATE_USER_PREFERENCES';

export const UPDATE_USER_FAVORITE_COINS = 'UPDATE_USER_FAVORITE_COINS';
export const GET_USER_FAVORITE_COINS = 'GET_USER_FAVORITE_COINS';

export const UPDATE_USER_NOTIFICATIONS = 'UPDATE_USER_NOTIFICATIONS';
export const GET_USER_NOTIFICATIONS = 'GET_USER_NOTIFICATIONS';

export const UPDATE_USER_SELECTED_COIN = 'UPDATE_USER_SELECTED_COIN';
export const GET_USER_SELECTED_COIN = 'GET_USER_SELECTED_COIN';


export const UPDATE_ALL_COINS = 'UPDATE_ALL_COINS';
export const GET_COIN_BY_ID = 'GET_COIN_BY_ID';


export const UPDATE_SELECTED_COIN = 'UPDATE_SELECTED_COIN';