export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_USER_PREFERENCES = 'UPDATE_USER_PREFERENCES';

export const UPDATE_USER_FAVORITE_COINS = 'UPDATE_USER_FAVORITE_COINS';
export const UPDATE_USER_NOTIFICATIONS = 'UPDATE_USER_NOTIFICATIONS';
export const UPDATE_USER_SELECTED_COIN = 'UPDATE_USER_SELECTED_COIN';


export const UPDATE_ALL_COINS = 'UPDATE_ALL_COINS';


export const UPDATE_SELECTED_COIN = 'UPDATE_SELECTED_COIN';



// DASHBOARD UI ACTIONS
export const UPDATE_CHART_TIMELINE = 'UPDATE_SELECTED_TIMELINE';
export const UPDATE_LOADING_INFO = 'UPDATE_LOADING_INFO';



// SOCKET SELECTED COIN EVENTS
export const RESET_INFO = 'RESET_INFO';
export const UPDATE_SELECTED_PRICES_LIST = 'UPDATE_SELECTED_PRICES_LIST';
export const UPDATE_SELECTED_VOLUME_DIFFERENCE = 'UPDATE_SELECTED_VOLUME_DIFFERENCE';
export const UPDATE_SELECTED_PRICE = 'UPDATE_SELECTED_PRICE';
export const UPDATE_SELECTED_PRICE_CHANGE = 'UPDATE_SELECTED_PRICE_CHANGE';
export const UPDATE_SELECTED_ORDER = 'UPDATE_SELECTED_ORDER';
export const UPDATE_SELECTED_PREVIOUS_ORDER = 'UPDATE_SELECTED_PREVIOUS_ORDER';
export const UPDATE_SELECTED_COUNT_ORDER = 'UPDATE_SELECTED_COUNT_ORDER';
export const UPDATE_SELECTED_COIN_MACD_DIFFERENCE = 'UPDATE_SELECTED_COIN_MACD_DIFFERENCE';

// SOCKET SPECIFIC COIN EVENTS
export const UPDATE_SPECIFIC_COIN_PRICES_LIST = 'UPDATE_SPECIFIC_COIN_PRICES_LIST';
export const UPDATE_SPECIFIC_COIN_VOLUME_DIFFERENCE = 'UPDATE_SPECIFIC_COIN_VOLUME_DIFFERENCE';
export const UPDATE_SPECIFIC_COIN_PRICE = 'UPDATE_SPECIFIC_COIN_PRICE';
export const UPDATE_SPECIFIC_COIN_PRICE_CHANGE = 'UPDATE_SPECIFIC_COIN_PRICE_CHANGE';
export const UPDATE_SPECIFIC_COIN_ORDER = 'UPDATE_SPECIFIC_COIN_ORDER';
export const UPDATE_SPECIFIC_COIN_PREVIOUS_ORDER = 'UPDATE_SPECIFIC_COIN_PREVIOUS_ORDER';
export const UPDATE_SPECIFIC_COIN_COUNT_ORDER = 'UPDATE_SPECIFIC_COIN_COUNT_ORDER';